name: maze-flatland
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python >3.9,<3.11
  - numpy<2.0.0
  - git
  - pip
  - pip:
      - flatland-rl==4.0.1
      - --extra-index-url https://download.pytorch.org/whl/cpu
      - torch==2.5.1+cpu
      - --find-links https://data.pyg.org/whl/torch-2.5.1+cpu.html
      - torch-scatter
      - hydra-nevergrad-sweeper==1.3.0.dev0
      # testing dependencies
      - pre-commit
      - pytest
      - pytest-cov
      - xgboost>=2.0.3
      - scikit-learn
